services:

  api:
    build: .
    container_name: zwiggy_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery_worker:
    build: .
    container_name: zwiggy_celery
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - postgres

  postgres:
    image: postgres:15
    container_name: zwiggy_postgres
    environment:
      POSTGRES_USER: zwiggy_admin
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: zwiggy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: zwiggy_redis
    ports:
      - "6379:6379"

  flower:
    image: mher/flower
    container_name: zwiggy_flower
    command: celery --broker=redis://redis:6379/0 flower
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  postgres_data: