"""initial tables

Revision ID: c6f8614b85e7
Revises: 
Create Date: 2026-03-05 13:39:26.361398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6f8614b85e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_restaurants_owner_id'), 'restaurants', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'restaurants', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_index(op.f('ix_restaurants_owner_id'), table_name='restaurants')
    op.drop_column('restaurants', 'owner_id')
    # ### end Alembic commands ###
